name: Deploy to S3

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Check S3_BUCKET
      run: echo "S3_BUCKET is ${{ vars.S3_BUCKET }}"

    - name: Upload datapipelinefile to S3
      run: |
        aws s3 cp data_pipeline.py s3://${{ vars.S3_BUCKET }}/dags/

    - name: Upload nyc_raw_to_transform.py to glue S3
      run: |
        aws s3 cp nyc_raw_to_transform.py s3://${{ vars.S3_BUCKET }}/scripts/glue/

    - name: Upload nyc_aggregations.py to emr S3
      run: |
        aws s3 cp nyc_aggregations.py s3://${{ vars.S3_BUCKET }}/scripts/emr/

    - name: Upload requirement to  S3
      run: |
        aws s3 cp requirements.txt s3://${{ vars.S3_BUCKET }}/requirements/


