name: Deploy to S3

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Upload file1.txt to S3
      run: |
        aws s3 cp data_pipeline.py s3://airflow-9449f8b0-631a-11ef-9521-0affe63809b1-bucket/dags/

    - name: Upload nyc_raw_to_transform.py to emr S3
      run: |
        aws s3 cp nyc_raw_to_transform.py s3://airflow-9449f8b0-631a-11ef-9521-0affe63809b1-bucket/scripts/emr/

    - name: Upload nyc_raw_to_transform.py to glue S3
      run: |
        aws s3 cp nyc_raw_to_transform.py s3://airflow-9449f8b0-631a-11ef-9521-0affe63809b1-bucket/scripts/emr/

    - name: Upload requirement to  S3
      ru
        aws s3 cp requirements.txt s3://airflow-9449f8b0-631a-11ef-9521-0affe63809b1-bucket/requirements/


