name: Deploy to S3

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Upload file1.txt to S3
      run: |
        aws s3 cp data_pipeline.py s3://testgithubformigration/2/

    - name: Upload nyc_raw_to_transform.py to S3
      run: |
        aws s3 cp nyc_raw_to_transform.py s3://testgithubformigration/1/

    - name: Upload nyc_raw_to_transform.py to S3
      run: |
        aws s3 cp nyc_raw_to_transform.py s3://testgithubformigration/3/

